"""FeedbackLog — stores user feedback + AI reflection for MCP/Skill results."""

from datetime import datetime, timezone

from sqlalchemy import DateTime, Integer, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


class FeedbackLogModel(Base):
    """User feedback on MCP/Skill execution results, with LLM reflection."""

    __tablename__ = "feedback_logs"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    # 'mcp' | 'skill'
    target_type: Mapped[str] = mapped_column(String(10), nullable=False, index=True)
    target_id: Mapped[int] = mapped_column(Integer, nullable=False, index=True)
    # User's free-text feedback about what went wrong
    user_feedback: Mapped[str] = mapped_column(Text, nullable=False, default="")
    # Summary of the previous result (e.g. "chart was empty", "wrong metric")
    previous_result_summary: Mapped[str] = mapped_column(Text, nullable=True)
    # LLM's reflection/analysis of why it went wrong
    llm_reflection: Mapped[str] = mapped_column(Text, nullable=True)
    # Revised processing_script generated by LLM after reflection
    revised_script: Mapped[str] = mapped_column(Text, nullable=True)
    # Whether the re-run after reflection succeeded
    rerun_success: Mapped[bool] = mapped_column(Integer, nullable=False, default=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False,
        default=lambda: datetime.now(tz=timezone.utc), server_default=func.now(),
    )
