"""SkillDefinition ORM model — the decision brain: event → MCPs → diagnosis."""

from datetime import datetime, timezone
from typing import Optional

from sqlalchemy import DateTime, ForeignKey, Integer, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


class SkillDefinitionModel(Base):
    """A Skill binds an EventType to one or more MCPs and provides diagnostic logic."""

    __tablename__ = "skill_definitions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    name: Mapped[str] = mapped_column(String(200), unique=True, nullable=False, index=True)
    description: Mapped[str] = mapped_column(Text, nullable=False, default="")
    event_type_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("event_types.id", ondelete="RESTRICT"), nullable=False, index=True
    )
    # JSON list of MCP definition IDs: [1, 2, 3]
    mcp_ids: Mapped[str] = mapped_column(Text, nullable=False, default="[]")
    # LLM auto-mapped + user-confirmed parameter bindings:
    # [{"event_field": str, "mcp_id": int, "mcp_param": str, "confidence": str}]
    param_mappings: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    # User-written diagnostic prompt using MCP output schema fields
    diagnostic_prompt: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    # Expert-authored human action recommendation (NOT generated by LLM)
    human_recommendation: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False,
        default=lambda: datetime.now(tz=timezone.utc), server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False,
        default=lambda: datetime.now(tz=timezone.utc), server_default=func.now(),
        onupdate=lambda: datetime.now(tz=timezone.utc),
    )

    def __repr__(self) -> str:
        return f"SkillDefinitionModel(id={self.id!r}, name={self.name!r})"
