package com.aiops.api.api.internal;

import com.aiops.api.auth.InternalAuthority;
import com.aiops.api.common.ApiException;
import com.aiops.api.common.ApiResponse;
import com.aiops.api.domain.blockdoc.BlockDocEntity;
import com.aiops.api.domain.blockdoc.BlockDocRepository;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import java.time.Instant;
import java.util.List;
import java.util.Optional;

/**
 * V49 (2026-05-19) — Block doc lookup for sidecar (catalog brief +
 * {@code inspect_block_doc}).
 *
 * <p>Sidecar fetches markdown source here instead of reading baked
 * descriptions from seed.py. Admin maintenance lives at the public
 * {@code /api/v1/block-docs} endpoints (separate controller).
 */
@RestController
@RequestMapping("/internal/block-docs")
@PreAuthorize(InternalAuthority.REQUIRE_SIDECAR)
public class InternalBlockDocController {

    private final BlockDocRepository repository;

    public InternalBlockDocController(BlockDocRepository repository) {
        this.repository = repository;
    }

    @GetMapping
    public ApiResponse<List<Dto>> list() {
        return ApiResponse.ok(repository.findAll().stream().map(Dto::of).toList());
    }

    @GetMapping("/{block_id}/{block_version}")
    public ApiResponse<Dto> get(@PathVariable("block_id") String blockId,
                                @PathVariable("block_version") String blockVersion) {
        Optional<BlockDocEntity> entity = repository
                .findByBlockIdAndBlockVersion(blockId, blockVersion);
        return ApiResponse.ok(Dto.of(entity.orElseThrow(
                () -> ApiException.notFound("block_doc"))));
    }

    /**
     * Upsert used by {@code tools/generate_block_docs.py} (auto-gen run).
     * Skips admin-edited rows unless caller sends {@code force=true}.
     */
    @PutMapping("/{block_id}/{block_version}")
    public ApiResponse<Dto> upsert(@PathVariable("block_id") String blockId,
                                   @PathVariable("block_version") String blockVersion,
                                   @RequestBody UpsertRequest req) {
        if (req == null || req.markdown() == null || req.markdown().isBlank()) {
            throw ApiException.badRequest("markdown is required");
        }
        Optional<BlockDocEntity> existing = repository
                .findByBlockIdAndBlockVersion(blockId, blockVersion);
        if (existing.isPresent()
                && Boolean.FALSE.equals(existing.get().getAutoGenerated())
                && !Boolean.TRUE.equals(req.force())) {
            // Admin-edited; skip silently (auto-gen scripts shouldn't clobber).
            return ApiResponse.ok(Dto.of(existing.get()));
        }
        BlockDocEntity entity = existing.orElseGet(() -> {
            BlockDocEntity fresh = new BlockDocEntity();
            fresh.setBlockId(blockId);
            fresh.setBlockVersion(blockVersion);
            return fresh;
        });
        entity.setMarkdown(req.markdown());
        entity.setSections(req.sections());
        entity.setAutoGenerated(Boolean.TRUE);
        entity.setLastEditedBy("auto-gen");
        entity.setLastEditedAt(Instant.now());
        return ApiResponse.ok(Dto.of(repository.save(entity)));
    }

    public record UpsertRequest(String markdown, String sections, Boolean force) {}

    /**
     * DTO carries full markdown + cached sections JSON. Sidecar typically
     * parses sections from cache to avoid re-running YAML+MD parse per
     * request.
     */
    public record Dto(Long id, String blockId, String blockVersion,
                      String markdown, String sections,
                      Boolean autoGenerated, String lastEditedBy,
                      java.time.Instant lastEditedAt,
                      java.time.OffsetDateTime createdAt) {
        static Dto of(BlockDocEntity e) {
            return new Dto(
                    e.getId(),
                    e.getBlockId(),
                    e.getBlockVersion(),
                    e.getMarkdown(),
                    e.getSections(),
                    e.getAutoGenerated(),
                    e.getLastEditedBy(),
                    e.getLastEditedAt(),
                    e.getCreatedAt()
            );
        }
    }
}
