"use client";

import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import Link from "next/link";

export default function BlockDocEditPage() {
  const params = useParams<{ block_id: string; block_version: string }>();
  const router = useRouter();
  const blockId = params.block_id;
  const blockVersion = params.block_version;

  const [markdown, setMarkdown] = useState("");
  const [autoGenerated, setAutoGenerated] = useState<boolean>(false);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [err, setErr] = useState<string | null>(null);
  const [savedMsg, setSavedMsg] = useState<string | null>(null);

  useEffect(() => {
    (async () => {
      try {
        const res = await fetch(
          `/api/block-docs/${blockId}/${blockVersion}`,
        );
        if (res.status === 404) {
          setMarkdown(buildStarterMarkdown(blockId));
          setLoading(false);
          return;
        }
        const body = await res.json();
        if (!res.ok) throw new Error(body?.message || `HTTP ${res.status}`);
        const doc = body?.data ?? body;
        setMarkdown(doc?.markdown ?? "");
        setAutoGenerated(!!doc?.autoGenerated);
      } catch (e) {
        setErr(e instanceof Error ? e.message : String(e));
      } finally {
        setLoading(false);
      }
    })();
  }, [blockId, blockVersion]);

  async function save() {
    setSaving(true);
    setSavedMsg(null);
    setErr(null);
    try {
      const res = await fetch(
        `/api/block-docs/${blockId}/${blockVersion}`,
        {
          method: "PUT",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ markdown }),
        },
      );
      const body = await res.json();
      if (!res.ok) throw new Error(body?.message || `HTTP ${res.status}`);
      setAutoGenerated(false);
      setSavedMsg("Saved.");
    } catch (e) {
      setErr(e instanceof Error ? e.message : String(e));
    } finally {
      setSaving(false);
    }
  }

  return (
    <div style={{ padding: 24, maxWidth: 1200, margin: "0 auto" }}>
      <div style={{ marginBottom: 12 }}>
        <Link href="/admin/block-docs" style={{ color: "#06f" }}>
          ← Back
        </Link>
      </div>
      <h1 style={{ fontSize: 18, marginBottom: 4 }}>
        <code>{blockId}</code> <span style={{ color: "#888" }}>v{blockVersion}</span>
        {autoGenerated && (
          <span style={{ marginLeft: 12, color: "#c70", fontSize: 12 }}>
            [auto-generated — pending admin review]
          </span>
        )}
      </h1>
      {loading && <p>Loading...</p>}
      {!loading && (
        <>
          <textarea
            value={markdown}
            onChange={(e) => setMarkdown(e.target.value)}
            style={{
              width: "100%",
              height: "70vh",
              fontFamily: "monospace",
              fontSize: 13,
              padding: 12,
              border: "1px solid #ccc",
              borderRadius: 4,
              marginTop: 12,
            }}
          />
          <div style={{ marginTop: 12, display: "flex", gap: 8, alignItems: "center" }}>
            <button
              onClick={save}
              disabled={saving}
              style={{
                padding: "6px 14px",
                background: "#06f",
                color: "white",
                border: 0,
                borderRadius: 4,
                cursor: "pointer",
              }}
            >
              {saving ? "Saving..." : "Save"}
            </button>
            {savedMsg && <span style={{ color: "#070" }}>{savedMsg}</span>}
            {err && <span style={{ color: "#c00" }}>{err}</span>}
          </div>
        </>
      )}
    </div>
  );
}

function buildStarterMarkdown(blockId: string): string {
  return `---
name: ${blockId}
description: <one-line headline used for catalog brief, ≤150 chars>
---

# ${blockId}

<2-4 line overview: what does it do + most important constraint.>

## When to invoke

- <use case 1>
- <use case 2>

不適用情境:
- <anti-case 1 → 改用 block_X>

## Inputs

### port: \`data\`
- type: <dataframe / chart_spec / scalar / dict>
- required: yes / no
- 期望狀態: <what upstream must have done>
- 必要欄位: <required columns>
- 不接受: <shapes that don't work>

upstream sample:
\`\`\`json
[{ ... }]
\`\`\`

## Outputs

### port: \`<port>\`
- type: ...
- shape: ...
- columns: ...
- 下游 hint: ...

output sample:
\`\`\`json
{ ... }
\`\`\`

## Parameters

| name | type | required | default | enum | 用途 |
|---|---|---|---|---|---|
| \`<name>\` | ... | ... | ... | ... | ... |

常見錯誤:
- ...

## Examples

### <pattern label>
\`\`\`
<upstream block> → ${blockId}(...)
\`\`\`
意圖: ...
注意: ...
`;
}
