"""Generate a deterministic, idempotent canonical block-seed SQL from the single
source of truth (python_ai_sidecar/pipeline_builder/seed.py:_blocks()).

Why (2026-06-23): pb_blocks has NO boot/deploy-time sync from the canonical
block list. The 56 blocks reached prod via Flyway (V1–V15) + manual psql for
later migrations (Flyway is disabled in prod). So a FRESH DB (a POC branch, a
new EC2) only gets whatever migrations actually ran → fewer/different blocks
than prod. This script emits one regenerable SQL that, applied to ANY database,
guarantees all canonical blocks EXIST.

Semantics: INSERT ... ON CONFLICT (name, version) DO NOTHING — insert-missing
ONLY. It never UPDATEs an existing row, so curated DB-only fields (examples,
hand-tuned descriptions) on an established DB are never clobbered; on prod it is
a pure no-op, on a fresh DB it backfills the full set.

Usage:
    python tools/gen_block_seed_sql.py > \
        java-backend/src/main/resources/db/canonical/pb_blocks_canonical.sql
"""
from __future__ import annotations

import json
import sys

from python_ai_sidecar.pipeline_builder.seed import _blocks

# Dollar-quote tag — chosen to never collide with block content. Verified below.
TAG = "$BLKSEED$"

# pb_blocks columns we populate (id is IDENTITY → omitted; mirrors V10 + source).
COLS = ("name", "version", "category", "status", "description",
        "input_schema", "output_schema", "param_schema", "implementation",
        "examples", "output_columns_hint", "is_custom", "source")


def _dq(value: str) -> str:
    """Dollar-quoted literal. Aborts if the tag appears in the value (would
    break quoting) — a loud failure beats a silently corrupt INSERT."""
    if TAG in value:
        raise SystemExit(f"FATAL: dollar tag {TAG} found inside a block value — "
                         f"pick a different TAG.")
    return f"{TAG}{value}{TAG}"


def _json(value) -> str:
    return _dq(json.dumps(value, ensure_ascii=False))


def main() -> None:
    blocks = _blocks()
    out = sys.stdout
    out.write("-- AUTO-GENERATED by tools/gen_block_seed_sql.py — DO NOT EDIT BY HAND.\n")
    out.write("-- Canonical block seed from python_ai_sidecar/pipeline_builder/seed.py.\n")
    out.write("-- Idempotent: ON CONFLICT (name, version) DO NOTHING (insert-missing only,\n")
    out.write("-- never clobbers curated rows). Apply to ANY pb_blocks DB to backfill the\n")
    out.write(f"-- full canonical set. {len(blocks)} blocks.\n\n")
    out.write("BEGIN;\n\n")
    for b in blocks:
        name = b["name"]
        vals = [
            _dq(name),
            _dq(b.get("version", "1.0.0")),
            _dq(b.get("category", "transform")),
            _dq(b.get("status", "production")),
            _dq(b.get("description", "")),
            _json(b.get("input_schema", [])),
            _json(b.get("output_schema", [])),
            _json(b.get("param_schema", {})),
            _json(b.get("implementation", {})),
            _json([]),  # examples — seed carries none; DO NOTHING preserves curated
            _json(b.get("output_columns_hint", [])),
            "false",                       # is_custom
            _dq("manual"),                 # source
        ]
        out.write(f"-- {name}\n")
        out.write("INSERT INTO pb_blocks\n  (" + ", ".join(COLS) + ")\nVALUES (\n  "
                  + ",\n  ".join(vals) + "\n)\nON CONFLICT (name, version) DO NOTHING;\n\n")
    out.write("COMMIT;\n")


if __name__ == "__main__":
    main()
