package com.aiops.api.domain.blockdoc;

import com.aiops.api.domain.common.Auditable;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * V49 (2026-05-19) — Block documentation as DB-stored Markdown.
 *
 * <p>Per CLAUDE.md core principle #1 (MCP / Block description = single
 * source of truth), each pipeline-builder block has a rich Markdown doc
 * stored here. Sidecar reads this for catalog brief and
 * {@code inspect_block_doc}; admin maintains via UI.
 *
 * <p>Markdown format follows the Claude SKILL.md convention:
 * <pre>
 *   ---
 *   name: block_xxx
 *   description: &lt;1-line headline used for catalog brief&gt;
 *   ---
 *   # block_xxx
 *   ## When to invoke
 *   ## Inputs
 *   ## Outputs
 *   ## Parameters
 *   ## Examples
 * </pre>
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "block_docs",
        indexes = {
                @Index(name = "idx_block_docs_block_id", columnList = "block_id"),
                @Index(name = "idx_block_docs_auto_generated", columnList = "auto_generated"),
        },
        uniqueConstraints = {
                @UniqueConstraint(name = "block_docs_uniq",
                        columnNames = {"block_id", "block_version"})
        }
)
public class BlockDocEntity extends Auditable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "block_id", nullable = false, length = 100)
    private String blockId;

    @Column(name = "block_version", nullable = false, length = 20)
    private String blockVersion = "1.0.0";

    /** Full markdown source (YAML frontmatter + body). */
    @Column(name = "markdown", nullable = false, columnDefinition = "text")
    private String markdown;

    /**
     * Parsed sections cache (JSON-as-text per repo convention).
     * Shape: {"description", "when_to_invoke", "inputs", "outputs",
     *         "parameters", "examples"}.
     * Populated by service on write; service falls back to parsing
     * {@link #markdown} when null.
     */
    @Column(name = "sections", columnDefinition = "text")
    private String sections;

    /**
     * TRUE = LLM-generated initial version, not admin-reviewed.
     * FALSE = admin manually edited; regenerate script skips by default.
     */
    @Column(name = "auto_generated", nullable = false)
    private Boolean autoGenerated = Boolean.TRUE;

    @Column(name = "last_edited_by", length = 120)
    private String lastEditedBy;

    @Column(name = "last_edited_at")
    private java.time.Instant lastEditedAt;
}
