package com.aiops.api.domain.blockdoc;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

@Repository
public interface BlockDocRepository extends JpaRepository<BlockDocEntity, Long> {

    Optional<BlockDocEntity> findByBlockIdAndBlockVersion(String blockId, String blockVersion);

    List<BlockDocEntity> findByBlockId(String blockId);

    List<BlockDocEntity> findByAutoGenerated(Boolean autoGenerated);

    boolean existsByBlockIdAndBlockVersion(String blockId, String blockVersion);
}
