package com.aiops.api.api.blockdoc;

import com.aiops.api.auth.AuthPrincipal;
import com.aiops.api.auth.Authorities;
import com.aiops.api.common.ApiException;
import com.aiops.api.common.ApiResponse;
import com.aiops.api.domain.blockdoc.BlockDocEntity;
import com.aiops.api.domain.blockdoc.BlockDocRepository;
import jakarta.validation.constraints.NotBlank;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import java.time.Instant;
import java.util.List;
import java.util.Map;

/**
 * V49 (2026-05-19) — Block doc admin CRUD.
 *
 * <p>Admin UI ({@code /admin/block-docs}) backs onto this. All write paths
 * require {@code IT_ADMIN} role per role hierarchy
 * ({@code project_oidc_auth.md}).
 *
 * <p>Sidecar uses {@link com.aiops.api.api.internal.InternalBlockDocController}
 * for reads (no JWT, internal token).
 */
@RestController
@RequestMapping("/api/v1/block-docs")
@Validated
public class BlockDocController {

    private final BlockDocRepository repository;

    public BlockDocController(BlockDocRepository repository) {
        this.repository = repository;
    }

    @GetMapping
    public ApiResponse<List<Dto>> list() {
        return ApiResponse.ok(repository.findAll().stream().map(Dto::of).toList());
    }

    @GetMapping("/{block_id}/{block_version}")
    public ApiResponse<Dto> get(@PathVariable("block_id") String blockId,
                                @PathVariable("block_version") String blockVersion) {
        return ApiResponse.ok(Dto.of(repository
                .findByBlockIdAndBlockVersion(blockId, blockVersion)
                .orElseThrow(() -> ApiException.notFound("block_doc"))));
    }

    /** Admin replace markdown. Sets auto_generated=false + audit fields. */
    @PutMapping("/{block_id}/{block_version}")
    @PreAuthorize(Authorities.ADMIN)
    public ApiResponse<Dto> update(@PathVariable("block_id") String blockId,
                                   @PathVariable("block_version") String blockVersion,
                                   @RequestBody UpdateRequest req,
                                   @AuthenticationPrincipal AuthPrincipal principal) {
        if (req == null || req.markdown() == null || req.markdown().isBlank()) {
            throw ApiException.badRequest("markdown is required");
        }
        BlockDocEntity entity = repository
                .findByBlockIdAndBlockVersion(blockId, blockVersion)
                .orElseGet(() -> {
                    BlockDocEntity fresh = new BlockDocEntity();
                    fresh.setBlockId(blockId);
                    fresh.setBlockVersion(blockVersion);
                    return fresh;
                });
        entity.setMarkdown(req.markdown());
        entity.setSections(req.sections());
        entity.setAutoGenerated(Boolean.FALSE);
        entity.setLastEditedBy(principal != null ? principal.username() : "unknown");
        entity.setLastEditedAt(Instant.now());
        BlockDocEntity saved = repository.save(entity);
        return ApiResponse.ok(Dto.of(saved));
    }

    /** Mark for re-generation (sidecar-side tools/generate_block_docs.py
     *  picks it up). Returns the row marked. */
    @PostMapping("/{block_id}/{block_version}/regenerate-flag")
    @PreAuthorize(Authorities.ADMIN)
    public ApiResponse<Map<String, Object>> regenerateFlag(
            @PathVariable("block_id") String blockId,
            @PathVariable("block_version") String blockVersion) {
        BlockDocEntity entity = repository
                .findByBlockIdAndBlockVersion(blockId, blockVersion)
                .orElseThrow(() -> ApiException.notFound("block_doc"));
        entity.setAutoGenerated(Boolean.TRUE);
        repository.save(entity);
        return ApiResponse.ok(Map.of(
                "block_id", blockId,
                "block_version", blockVersion,
                "marked_for_regen", true
        ));
    }

    public record UpdateRequest(@NotBlank String markdown, String sections) {}

    public record Dto(Long id, String blockId, String blockVersion,
                      String markdown, String sections,
                      Boolean autoGenerated, String lastEditedBy,
                      Instant lastEditedAt,
                      java.time.OffsetDateTime createdAt) {
        static Dto of(BlockDocEntity e) {
            return new Dto(
                    e.getId(), e.getBlockId(), e.getBlockVersion(),
                    e.getMarkdown(), e.getSections(),
                    e.getAutoGenerated(), e.getLastEditedBy(),
                    e.getLastEditedAt(),
                    e.getCreatedAt()
            );
        }
    }
}
